LiPP_path: "data/LiPP_csvfiles/<name-of-the-set>.csv"
pdb_path: "data/pdb_structures_split"
pdb_complex_path: "data/pdb_structures_complex"
conda_path: "<path-to-conda-envs>/.conda/envs"
AF3_path: "<path-to-alphafold3-installation>/alphafold3"
AF3_image_path: "<path-to-alphafold3-image>/alphafold3/image.sif"
AF3_database_path: "<path-to-alphafold3-database>/alphafold3_database"
AF3_param_path: "<path-to-alphafold3-params>/alphafold3_param"
AutoDockVina_path: "<path-to-autodock-vina-installation>/bin/vina"
RFAA_path: "<path-to-rosettafoldallatom>/RoseTTAFold-All-Atom"
